name: decomposition-shap
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn
  - xgboost
  - matplotlib
  - pandas
  - shap=0.35.0
  - pytest
  - statsmodels
  - pingouin
